-- Execute with an appropriately privileged Snowflake security role.
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS DATA_SCIENTIST;
GRANT USAGE ON DATABASE ENTERPRISE_MEDALLION_DB TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA ENTERPRISE_MEDALLION_DB.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA ENTERPRISE_MEDALLION_DB.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ENTERPRISE_MEDALLION_DB.GOLD TO ROLE DATA_ANALYST;
