-- Run with a role authorized to create databases/schemas.
CREATE DATABASE IF NOT EXISTS ENTERPRISE_MEDALLION_DB;

CREATE SCHEMA IF NOT EXISTS ENTERPRISE_MEDALLION_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_MEDALLION_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_MEDALLION_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_MEDALLION_DB.MONITORING;
